management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

example:
  property: 'I AM THE DEFAULT'

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=licensing_service

logging:
  level:
    com.optimagrowth.licensing.service: DEBUG
