spring:
  cloud:
    gateway:
      discovery:
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/licensing/**
          filters:
            - RewritePath=/licensing/(?<path>.*), /$\{path}
